public enum TokenType {
    KEYWORD,
    IDENTIFIER,
    NUMBER,
    STRING,
    OPERATOR,
    SEPARATOR,
    COMMENT,
    UNKNOWN,
    OPERAND,
    LEFT_PARENTHESIS,
    RIGHT_PARENTHESIS,
    CONTROL_STRUCTURE,
}
